# Generated by Django 4.2.7 on 2023-12-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.CharField(max_length=10)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("food", "Food"), ("drink", "Drink")], max_length=10
                    ),
                ),
            ],
            options={
                "db_table": "driftwood_tavern_menu",
            },
        ),
    ]
