# Generated by Django 4.2.7 on 2023-12-03 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="menu",
            table="dwt_menu_items",
        ),
    ]
