# Generated by Django 4.2.7 on 2023-12-03 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_menu", "0002_alter_menu_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={"verbose_name_plural": "Menu Items"},
        ),
    ]
