# Generated by Django 4.2.7 on 2023-12-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_menu", "0003_alter_menu_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="price",
        ),
        migrations.AddField(
            model_name="menu",
            name="currency",
            field=models.CharField(
                choices=[
                    ("cp", "cp"),
                    ("sp", "sp"),
                    ("ep", "ep"),
                    ("gp", "gp"),
                    ("pp", "pp"),
                ],
                default="cp",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="price_amount",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
