# Generated by Django 4.2.7 on 2023-12-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_menu", "0005_alter_menu_currency_alter_menu_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="item_type",
            field=models.CharField(
                choices=[("food", "Food"), ("drink", "Drink")], max_length=10
            ),
        ),
    ]
